#!/usr/bin/env php
<?php

// Continue only if application is ran from CLI
!strcmp(php_sapi_name(), 'cli') or exit('Run only from cli.');

// Require lollipop-php
require_once('./vendor/autoload.php');
// Load web application configuration and routes
require_once('./core/bootstrap.php');

spl_autoload_register(function ($class) {
    // project-specific namespace prefix
    $prefix = 'bin\\';

    // base directory for the namespace prefix
    $base_dir = dirname(__FILE__) . '/bin/';
    
    // does the class use the namespace prefix?
    $len = strlen($prefix);
    if (strncmp($prefix, $class, $len) !== 0) {
        // no, move to the next registered autoloader
        return;
    }

    // get the relative class name
    $relative_class = substr($class, $len);

    // replace the namespace prefix with the base directory, replace namespace
    // separators with directory separators in the relative class name, append
    // with .php
    $file = $base_dir . str_replace('\\', '/', $relative_class) . '.php';

    // if the file exists, require it
    if (file_exists($file)) {
        require $file;
    }
});

// Create \Console\Application
$app = new \Console\Application();

// Registered commands
// - cache command
$app->add('cache', new \bin\Cache());

// Register new commands here...

// Run application
$app->run();
