#!/usr/bin/env php
<?php

// Continue only if application is ran from CLI
!strcmp(php_sapi_name(), 'cli') or exit('Run only from cli.');

// Require lollipop-php
require_once('./vendor/autoload.php');
// Import command library autoloader
require_once('./bin/autoload.php');
// Load web application configuration and routes
require_once('./core/bootstrap.php');

// Create \Console\Application
$app = new \Console\Application();

// Registered commands
// - cache command
$app->add('cache',  new \App\Command\Cache());
$app->add('route',  new \App\Command\Route());

// Register new commands here...

// Run application
$app->run();
