#!/usr/bin/php
<?php

// Continue only if application is ran from CLI
!strcmp(php_sapi_name(), 'cli') or exit('Run only from cli.');

// Declare application paths
define('APP_ROOT', realpath(dirname(__FILE__)));
define('APP_CORE', APP_ROOT . '/app/');
define('APP_CORE_CONTROLLER', APP_CORE . 'controller/');
define('APP_CORE_MODEL', APP_CORE . 'model/');
define('APP_CORE_VIEW', APP_CORE . 'view/');
define('APP_CORE_HELPER', APP_CORE . 'helper/');
define('APP_CORE_CACHE', APP_CORE . 'cache/');
define('APP_CORE_LOG', APP_CORE . 'log/');
define('APP_CORE_DB', APP_CORE . 'db/');
define('APP_CORE_DEBUG', APP_CORE . 'debug/');
define('APP_BIN', APP_ROOT . '/bin/');
define('APP_BIN_GENERATE', APP_BIN . 'Generate/');
define('APP_BIN_GENERATE_TEMPLATES', APP_BIN_GENERATE . 'Templates/');

// Command-line colors
define('CF_BLACK',  "\033[30m");
define('CF_RED',    "\033[31m");
define('CF_GREEN',  "\033[32m");
define('CF_BROWN',  "\033[33m");
define('CF_BLUE',   "\033[34m");
define('CF_MAGENTA',"\033[35m");
define('CF_CYAN',   "\033[36m");
define('CF_WHITE',  "\033[37m");
define('CF_RESET',  "\033[39m");

// Check if config is active in current directory
if (!file_exists(APP_CORE . 'config.php')) {
    exit(CF_RED . 'LMVC config not found.' . CF_RESET . PHP_EOL);
}

// Parse configuration file
require_once(APP_CORE . 'config.php');

if (!isset($config) && !isset($config['app']) && !is_array($config['app'])) {
    exit(CF_RED . 'LMVC invalid config file.' . CF_RESET . PHP_EOL);
}

// Export configuration from project
$proj_config = [
        'package' => isset($config['app']['name']) ? $config['app']['name'] : 'Application Name',
        'version' => isset($config['app']['version']) ? $config['app']['version'] : '1.0',
        'author' => isset($config['app']['author']) ? $config['app']['author'] : 'Programmer',
    ];

// @var     array   Commands for application
$commands = [
        'generate' => [
                'name' => 'Generate',
                'path' => APP_BIN_GENERATE . '/Generate.php'
            ]
    ];

// Get first main parameter from command line
// if there is no parameter just set it to null
$cmd_main = isset($argv[1]) ? strtolower($argv[1]) : null;

if (!$cmd_main) {
    exit(CF_RED . 'No parameters found.' . CF_RESET . PHP_EOL);
}

if (isset($commands[$cmd_main])) {
    // Get command information
    $cmd_info = $commands[$cmd_main];

    // Get other parameters after main command
    $params = array_splice($argv, 2, count($argv) - 1);
    
    // Load command class
    require_once($cmd_info['path']);
    
    $cmd = new $cmd_info['name']($proj_config, $params);
    
} else {
    // Commamd is unknown
    exit(CF_RED . 'Command not found: ' . CF_RESET . $cmd_main . PHP_EOL);    
}
